# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [2]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [3]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)
e = np.arange(0,69,1)

What are these functions?

    arange?

In [3]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[1, 5, 9, 5],
         [1, 3, 9, 5],
         [1, 9, 4, 7]],
 
        [[5, 5, 5, 1],
         [4, 3, 7, 2],
         [1, 7, 3, 1]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
## Arithmetic in arrays is element wise

In [4]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [5]:
c = a-b
c

array([20, 29, 38, 47])

In [4]:
swag = [i**2 for i in range(58)]

In [6]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [7]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [8]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
a[2:5]

array([ 4,  9, 16])

In [10]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [11]:
b = np.random.randint(1,100,(4,4))

In [12]:
b

array([[14, 56,  6, 16],
       [48, 43, 77, 26],
       [11, 37, 45, 18],
       [ 2, 10, 81, 97]])

In [13]:
# Guess the output
print(b[2,3])
print(b[0,0])


18
14


In [14]:
b[0:3,1],b[:,1]

(array([56, 43, 37]), array([56, 43, 37, 10]))

In [15]:
b[1:3,:]

array([[48, 43, 77, 26],
       [11, 37, 45, 18]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [19]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  2.604552 -0.286448  0.572294 -1.081954
2014-01-02 -0.143596  0.403645  2.695791 -0.767807
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423
2014-01-04 -0.717657 -0.740800  0.938863  0.957629
2014-01-05 -0.522290  1.646924  1.183220 -1.070110
2014-01-06 -1.175909 -0.837163 -1.736440  0.697748

In [20]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [21]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [22]:
df.head()

A         B         C         D
2014-01-01  2.604552 -0.286448  0.572294 -1.081954
2014-01-02 -0.143596  0.403645  2.695791 -0.767807
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423
2014-01-04 -0.717657 -0.740800  0.938863  0.957629
2014-01-05 -0.522290  1.646924  1.183220 -1.070110

In [23]:
df.tail()

A         B         C         D
2014-01-02 -0.143596  0.403645  2.695791 -0.767807
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423
2014-01-04 -0.717657 -0.740800  0.938863  0.957629
2014-01-05 -0.522290  1.646924  1.183220 -1.070110
2014-01-06 -1.175909 -0.837163 -1.736440  0.697748

In [24]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [25]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.104277 -0.003153  0.480330 -0.230486
std    1.368179  0.921842  1.555815  0.894927
min   -1.175909 -0.837163 -1.736440 -1.081954
25%   -0.705934 -0.627212 -0.435739 -0.994534
50%   -0.596528 -0.245763  0.755579 -0.443115
75%   -0.238269  0.251465  1.122131  0.493706
max    2.604552  1.646924  2.695791  0.957629

In [26]:
df.sort_values(by='B')
df

A         B         C         D
2014-01-01  2.604552 -0.286448  0.572294 -1.081954
2014-01-02 -0.143596  0.403645  2.695791 -0.767807
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423
2014-01-04 -0.717657 -0.740800  0.938863  0.957629
2014-01-05 -0.522290  1.646924  1.183220 -1.070110
2014-01-06 -1.175909 -0.837163 -1.736440  0.697748

### Selection

In [27]:
df[['A','B']]

A         B
2014-01-01  2.604552 -0.286448
2014-01-02 -0.143596  0.403645
2014-01-03 -0.670766 -0.205077
2014-01-04 -0.717657 -0.740800
2014-01-05 -0.522290  1.646924
2014-01-06 -1.175909 -0.837163

In [28]:
df[0:3]

A         B         C         D
2014-01-01  2.604552 -0.286448  0.572294 -1.081954
2014-01-02 -0.143596  0.403645  2.695791 -0.767807
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423

In [29]:
# By label
df.loc[dates[0]]

A    2.604552
B   -0.286448
C    0.572294
D   -1.081954
Name: 2014-01-01 00:00:00, dtype: float64

In [30]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  2.604552 -0.286448
2014-01-02 -0.143596  0.403645
2014-01-03 -0.670766 -0.205077
2014-01-04 -0.717657 -0.740800
2014-01-05 -0.522290  1.646924
2014-01-06 -1.175909 -0.837163

In [31]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02  0.403645
2014-01-03 -0.205077
2014-01-04 -0.740800

In [32]:
# Fast access to scalar
df.at[dates[1],'B']

0.40364540366068768

In [33]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04 -0.717657 -0.740800  0.938863  0.957629
2014-01-05 -0.522290  1.646924  1.183220 -1.070110
2014-01-06 -1.175909 -0.837163 -1.736440  0.697748

### Boolean Indexing

In [34]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-02 -0.143596  0.403645  2.695791 -0.767807
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423
2014-01-04 -0.717657 -0.740800  0.938863  0.957629
2014-01-05 -0.522290  1.646924  1.183220 -1.070110
2014-01-06 -1.175909 -0.837163 -1.736440  0.697748

### Setting

In [35]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [36]:
df_posA

A         B         C         D
2014-01-01  2.604552 -0.286448  0.572294 -1.081954
2014-01-02  0.143596 -0.403645 -2.695791  0.767807
2014-01-03  0.670766  0.205077  0.771750  0.118423
2014-01-04  0.717657  0.740800 -0.938863 -0.957629
2014-01-05  0.522290 -1.646924 -1.183220  1.070110
2014-01-06  1.175909  0.837163  1.736440 -0.697748

In [37]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [38]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [39]:
df['F'] = s1

In [40]:
df

A         B         C         D    F
2014-01-01  2.604552 -0.286448  0.572294 -1.081954  NaN
2014-01-02 -0.143596  0.403645  2.695791 -0.767807  1.0
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423  2.0
2014-01-04 -0.717657 -0.740800  0.938863  0.957629  3.0
2014-01-05 -0.522290  1.646924  1.183220 -1.070110  4.0
2014-01-06 -1.175909 -0.837163 -1.736440  0.697748  5.0

### Missing Data

In [41]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [42]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [43]:
df1

A         B         C         D    F    E
2014-01-01  2.604552 -0.286448  0.572294 -1.081954  NaN  1.0
2014-01-02 -0.143596  0.403645  2.695791 -0.767807  1.0  1.0
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423  2.0  NaN
2014-01-04 -0.717657 -0.740800  0.938863  0.957629  3.0  NaN

In [44]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [45]:
df.describe()

C:\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.104277 -0.003153  0.480330 -0.230486  3.000000
std    1.368179  0.921842  1.555815  0.894927  1.581139
min   -1.175909 -0.837163 -1.736440 -1.081954  1.000000
25%   -0.705934 -0.627212 -0.435739 -0.994534       NaN
50%   -0.596528 -0.245763  0.755579 -0.443115       NaN
75%   -0.238269  0.251465  1.122131  0.493706       NaN
max    2.604552  1.646924  2.695791  0.957629  5.000000

In [46]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.104277
 B   -0.003153
 C    0.480330
 D   -0.230486
 F    3.000000
 dtype: float64, 2014-01-01    0.452111
 2014-01-02    0.637607
 2014-01-03    0.046797
 2014-01-04    0.687607
 2014-01-05    1.047549
 2014-01-06    0.389647
 Freq: D, dtype: float64)

### Applying functions

In [47]:
df

A         B         C         D    F
2014-01-01  2.604552 -0.286448  0.572294 -1.081954  NaN
2014-01-02 -0.143596  0.403645  2.695791 -0.767807  1.0
2014-01-03 -0.670766 -0.205077 -0.771750 -0.118423  2.0
2014-01-04 -0.717657 -0.740800  0.938863  0.957629  3.0
2014-01-05 -0.522290  1.646924  1.183220 -1.070110  4.0
2014-01-06 -1.175909 -0.837163 -1.736440  0.697748  5.0

In [48]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  2.604552 -0.286448  0.572294 -1.081954   NaN
2014-01-02  2.460956  0.117197  3.268085 -1.849761   1.0
2014-01-03  1.790191 -0.087880  2.496335 -1.968184   3.0
2014-01-04  1.072534 -0.828680  3.435198 -1.010555   6.0
2014-01-05  0.550244  0.818243  4.618418 -2.080665  10.0
2014-01-06 -0.625664 -0.018920  2.881977 -1.382917  15.0

In [49]:
df.apply(lambda x: x.max() - x.min())

A    3.780461
B    2.484087
C    4.432231
D    2.039583
F    4.000000
dtype: float64

In [50]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [51]:
np.random.randn(10,4)

array([[ 0.86976922,  0.41924656, -0.60521986, -0.5509494 ],
       [-1.17809544, -1.46277205, -0.27205101,  0.28842046],
       [-1.55306908,  0.39248699,  0.25781516, -1.75059206],
       [ 0.10509324, -0.33411699,  2.31572111, -1.58645642],
       [ 0.56210577, -0.73141426,  0.80884112, -0.3935214 ],
       [ 1.00397716,  1.08006504, -0.60517295,  1.68190537],
       [ 0.78039265, -0.28501125, -1.47135063,  1.26196883],
       [-1.00548077, -1.20723213,  0.02518183,  0.27397444],
       [-1.14215311, -0.88854792, -2.00158912,  1.22479521],
       [ 0.96444882, -0.78135193,  1.27145425, -1.2701375 ]])

In [52]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -1.011598 -0.067276 -0.329718  1.854843
1 -0.689516 -0.793863 -0.934505  0.120608
2  1.252760  0.626642 -0.327524  1.243904
3  1.459666 -0.601071 -0.575780 -0.161793
4 -1.046668  1.742103  1.107985  1.075856
5 -0.099130 -1.756687  1.578114  1.726804
6  0.583566  1.047002 -0.672197  0.075251
7 -0.507451  0.365866  0.938717 -0.468684
8  1.845038 -1.665816 -0.311175  0.998069
9  1.302166  0.824490  1.304442 -0.432103

In [53]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -1.011598 -0.067276 -0.329718  1.854843
 1 -0.689516 -0.793863 -0.934505  0.120608
 2  1.252760  0.626642 -0.327524  1.243904,
           0         1         2         3
 3  1.459666 -0.601071 -0.575780 -0.161793
 4 -1.046668  1.742103  1.107985  1.075856
 5 -0.099130 -1.756687  1.578114  1.726804
 6  0.583566  1.047002 -0.672197  0.075251,
           0         1         2         3
 7 -0.507451  0.365866  0.938717 -0.468684
 8  1.845038 -1.665816 -0.311175  0.998069
 9  1.302166  0.824490  1.304442 -0.432103]

In [54]:
pd.concat(pieces)

0         1         2         3
0 -1.011598 -0.067276 -0.329718  1.854843
1 -0.689516 -0.793863 -0.934505  0.120608
2  1.252760  0.626642 -0.327524  1.243904
3  1.459666 -0.601071 -0.575780 -0.161793
4 -1.046668  1.742103  1.107985  1.075856
5 -0.099130 -1.756687  1.578114  1.726804
6  0.583566  1.047002 -0.672197  0.075251
7 -0.507451  0.365866  0.938717 -0.468684
8  1.845038 -1.665816 -0.311175  0.998069
9  1.302166  0.824490  1.304442 -0.432103

In [55]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -1.011598 -0.067276 -0.329718  1.854843
1 -0.689516 -0.793863 -0.934505  0.120608
2  1.252760  0.626642 -0.327524  1.243904
3  1.459666 -0.601071 -0.575780 -0.161793
4 -1.046668  1.742103  1.107985  1.075856
5 -0.099130 -1.756687  1.578114  1.726804
6  0.583566  1.047002 -0.672197  0.075251
7 -0.507451  0.365866  0.938717 -0.468684
8  1.845038 -1.665816 -0.311175  0.998069
9  1.302166  0.824490  1.304442 -0.432103

### Grouping


In [56]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [57]:
df

A      B         C         D
0  foo    one -0.908846  0.500105
1  bar    one  1.387580  0.487386
2  foo    two  0.176139 -1.225147
3  bar  three  0.193776  0.371895
4  foo    two -2.138062  1.376119
5  bar    two -1.208470 -0.360151
6  foo    one  0.495383 -1.203684
7  foo  three -0.550592 -1.516866

In [ ]:
df.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas